"""
LLM and embedding helper functions (stub implementations for MVP).
TODO: Replace with real OpenAI API calls later.
"""

import math
import random
from typing import List
from models import IdeaNode
import storage


def call_llm(role: str, prompt: str, max_tokens: int = 500) -> str:
    """
    Stub function to call an LLM.

    TODO: Replace with actual OpenAI API call.

    Args:
        role: The role/context for the LLM call (e.g., "overseer_init", "agent_opening")
        prompt: The prompt to send to the LLM
        max_tokens: Maximum tokens in response

    Returns:
        LLM response as a string (currently returns dummy text with council footer)
    """
    # For MVP, return dummy responses based on role
    if role == "overseer_init":
        return f"Initial analysis of the user's question. This is a placeholder overseer summary that would normally be generated by an LLM based on the user prompt."

    elif role == "overseer_update":
        return f"Updated overseer summary after reviewing council deliberations. The council has explored various perspectives and key themes are emerging."

    elif role == "overseer_synthesis":
        return """Based on the council's deliberations, here is the synthesized answer:

The council has explored multiple perspectives on this topic. Key insights include consideration of various approaches, trade-offs, and potential solutions.

[COUNCIL_STATE]
{
  "final_answer": "This is a placeholder final answer synthesized from council deliberations.",
  "council_summary": "The council engaged in thoughtful debate, exploring multiple angles and reaching a balanced conclusion."
}
[/COUNCIL_STATE]"""

    elif role.startswith("agent_opening"):
        agent_num = role.split("_")[-1] if "_" in role else "1"
        return f"""Here is my opening stance on this topic.

As an agent with my particular perspective, I believe we should consider approach {agent_num}. This involves examining the core assumptions and exploring alternative framings. My initial analysis suggests several key factors to investigate further.

[COUNCIL_STATE]
{{
  "current_node_id": "node_opening_{agent_num}",
  "status": "ACTIVE",
  "new_branch_proposals": [],
  "votes": {{}},
  "raise_objection_to": null
}}
[/COUNCIL_STATE]"""

    elif role.startswith("agent_debate"):
        agent_num = role.split("_")[-1] if "_" in role else "1"
        return f"""I'd like to build on the previous points raised.

From my perspective as agent {agent_num}, I see merit in exploring this direction further. However, we should also consider potential edge cases and alternative interpretations. Let me propose a refinement to the current thinking.

[COUNCIL_STATE]
{{
  "current_node_id": "node_debate_{agent_num}_{random.randint(1000, 9999)}",
  "status": "ACTIVE",
  "new_branch_proposals": [],
  "votes": {{}},
  "raise_objection_to": null
}}
[/COUNCIL_STATE]"""

    else:
        return f"Placeholder LLM response for role: {role}\n\n[COUNCIL_STATE]\n{{}}\n[/COUNCIL_STATE]"


def get_embedding(text: str) -> List[float]:
    """
    Stub function to get text embeddings.

    TODO: Replace with actual OpenAI embeddings API call.

    Args:
        text: Text to embed

    Returns:
        Embedding vector (currently returns a dummy 384-dimensional vector)
    """
    # For MVP, return a dummy embedding vector
    # Use a simple hash-based approach for consistency
    random.seed(hash(text) % 2**32)
    embedding = [random.random() for _ in range(384)]

    # Normalize the vector
    magnitude = math.sqrt(sum(x**2 for x in embedding))
    normalized = [x / magnitude for x in embedding]

    return normalized


def cosine_similarity(vec1: List[float], vec2: List[float]) -> float:
    """
    Calculate cosine similarity between two vectors.

    Args:
        vec1: First vector
        vec2: Second vector

    Returns:
        Cosine similarity score between -1 and 1
    """
    if len(vec1) != len(vec2):
        raise ValueError("Vectors must have the same dimension")

    dot_product = sum(a * b for a, b in zip(vec1, vec2))

    # If vectors are already normalized, dot product is the cosine similarity
    # For safety, compute magnitudes
    mag1 = math.sqrt(sum(a**2 for a in vec1))
    mag2 = math.sqrt(sum(b**2 for b in vec2))

    if mag1 == 0 or mag2 == 0:
        return 0.0

    return dot_product / (mag1 * mag2)


def similarity_search_nodes(
    query_embedding: List[float],
    conversation_id: str,
    top_k: int = 5,
    exclude_ids: List[str] = None
) -> List[tuple[IdeaNode, float]]:
    """
    Search for similar nodes using cosine similarity.

    Args:
        query_embedding: Query embedding vector
        conversation_id: Limit search to this conversation
        top_k: Number of top results to return
        exclude_ids: Node IDs to exclude from results

    Returns:
        List of (node, similarity_score) tuples, sorted by similarity (highest first)
    """
    exclude_ids = exclude_ids or []

    # Get all nodes for the conversation
    conv_nodes = storage.get_nodes_for_conversation(conversation_id)

    # Calculate similarities
    results = []
    for node in conv_nodes:
        if node.id in exclude_ids:
            continue

        similarity = cosine_similarity(query_embedding, node.embedding)
        results.append((node, similarity))

    # Sort by similarity (descending) and return top k
    results.sort(key=lambda x: x[1], reverse=True)
    return results[:top_k]


def search_nodes(query: str, conversation_id: str, k: int = 5) -> List[IdeaNode]:
    """
    Search for relevant nodes using semantic search.

    TODO: This is a placeholder for RAG functionality.

    Args:
        query: Search query
        conversation_id: Limit search to this conversation
        k: Number of results

    Returns:
        List of relevant nodes
    """
    # Get embedding for query
    query_embedding = get_embedding(query)

    # Search for similar nodes
    results = similarity_search_nodes(query_embedding, conversation_id, top_k=k)

    # Return just the nodes (without scores)
    return [node for node, score in results]


def search_transcript(query: str, conversation_id: str, k: int = 5) -> List:
    """
    Search transcript messages using semantic search.

    TODO: This is a placeholder for RAG functionality.
    Would need to embed messages and do similarity search.

    Args:
        query: Search query
        conversation_id: Limit search to this conversation
        k: Number of results

    Returns:
        List of relevant messages
    """
    # TODO: Implement transcript search
    # For now, just return empty list
    return []
